-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 15:10:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbtaw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbtaw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtaw` DEFAULT CHARACTER SET utf8 ;
USE `dbtaw` ;

-- -----------------------------------------------------
-- Table `dbtaw`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Docente` (
  `rut` INT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `cargo_adm` VARCHAR(2) NULL,
  CONSTRAINT docente_pk PRIMARY KEY (`rut`),
  CONSTRAINT cargo_adm_chk CHECK (cargo_adm in ('jc', 'da')))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Bloque` (
  `idBloque` INT AUTO_INCREMENT,
  `dia` VARCHAR(2) NOT NULL,
  `n_bloque` INT NOT NULL,
  CONSTRAINT bloque_pk PRIMARY KEY (`idBloque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Carrera` (
  `codigo` INT,
  `nombre` VARCHAR(45) NULL,
  `da_rut` INT NULL,
  `jc_rut` INT NULL,
  CONSTRAINT carrera_pk PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_Carrera_da`
    FOREIGN KEY (`da_rut`)
    REFERENCES `dbtaw`.`Docente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrera_jc`
    FOREIGN KEY (`jc_rut`)
    REFERENCES `dbtaw`.`Docente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Plan estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Plan estudio` (
  `año` INT,
  `idCarrera` INT,
  `semestre` INT NOT NULL,
  CONSTRAINT plan_estudio_pk PRIMARY KEY (`año`, `idCarrera`),
  CONSTRAINT `fk_plan_carrera`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `dbtaw`.`Carrera` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Departamento` (
  `idDep` INT,
  `nombre` VARCHAR(45) NOT NULL,
  `sede` VARCHAR(45) NOT NULL,
  CONSTRAINT dep_pk PRIMARY KEY (`idDep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Sala` (
  `idSala` INT,
  `nombre` VARCHAR(45) NOT NULL,
  `idDep` INT NOT NULL,
  CONSTRAINT sala_pk PRIMARY KEY (`idSala`),
  CONSTRAINT `fk_Sala_Departamento`
    FOREIGN KEY (`idDep`)
    REFERENCES `dbtaw`.`Departamento` (`idDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`disponible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`disponible` (
  `Docente_rut` INT,
  `idBloque` INT,
  `usado` INT NOT NULL,
  CONSTRAINT dispo_pk PRIMARY KEY (`Docente_rut`, `idBloque`),
  CONSTRAINT `fk_Docente_has_Bloque_Docente1`
    FOREIGN KEY (`Docente_rut`)
    REFERENCES `dbtaw`.`Docente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docente_has_Bloque_Bloque1`
    FOREIGN KEY (`idBloque`)
    REFERENCES `dbtaw`.`Bloque` (`idBloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Ramo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Ramo` (
  `codigo` VARCHAR(5),
  `nombre` VARCHAR(45) NOT NULL,
  `max_bloques` INT NOT NULL,
  CONSTRAINT ramo_pk PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Asignacion` (
  `idRamo` INT,
  `idSala` INT,
  `Docente_rut` INT NULL,
  `idBloque` INT NOT NULL,
  `grupo` VARCHAR(1) NOT NULL,
  CONSTRAINT asignacion_pk PRIMARY KEY (`idRamo`, `idSala`),
  CONSTRAINT `fk_Ramo_has_Sala_Ramo1`
    FOREIGN KEY (`idRamo`)
    REFERENCES `dbtaw`.`Ramo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ramo_has_Sala_Sala1`
    FOREIGN KEY (`idSala`)
    REFERENCES `dbtaw`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ramo_has_Sala_Docente1`
    FOREIGN KEY (`Docente_rut`)
    REFERENCES `dbtaw`.`Docente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Bloque1`
    FOREIGN KEY (`idBloque`)
    REFERENCES `dbtaw`.`Bloque` (`idBloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`imparte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`imparte` (
  `rut` INT,
  `idRamo` INT,
  CONSTRAINT imparte_pk PRIMARY KEY (`rut`, `idRamo`),
  CONSTRAINT `fk_Docente_has_Ramo_Docente1`
    FOREIGN KEY (`rut`)
    REFERENCES `dbtaw`.`Docente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docente_has_Ramo_Ramo1`
    FOREIGN KEY (`idRamo`)
    REFERENCES `dbtaw`.`Ramo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtaw`.`Malla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtaw`.`Malla` (
  `año` INT,
  `idCarrera` INT,
  `codigo` INT,
  `num_semestre` INT NOT NULL,
  CONSTRAINT malla_pk PRIMARY KEY (`año`, `idCarrera`, `codigo`),
  CONSTRAINT `fk_Malla_Plan estudio1`
    FOREIGN KEY (`año` , `idCarrera`)
    REFERENCES `dbtaw`.`Plan estudio` (`año` , `idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Malla_Ramo1`
    FOREIGN KEY (`codigo`)
    REFERENCES `dbtaw`.`Ramo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
